modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Wynd/MineMineNoMi3/issues"

[[mods]]
modId="mineminenomi"
version="0.6.2"
displayName="Mine Mine no Mi"
displayURL="https://www.pixelatedw.xyz/"
logoFile="examplemod.png"
authors="Wynd"
description='''
Mine Mine no Mi is a minecraft mod inspired by the famous anime/manga series One Piece written and illustrated by Eiichiro Oda. It aims to be an adventure oriented mod where exploration is one of the key features.

Dev Team :
    Wynd - Progammer 
    FGpisces - 2D Artist, QA 
    Kenryuu - QA 
    DragonLuch - 3D Artist 
    Izako - Programmer 
    Zankrid - Programmer

Patreons :
    Hermano 
    kiopt 
    Sergio Iucci 
    M4DN3SS 
    Izable 
    山嵜　
    順之輔 
    Beosti 
    TheOmniscientBear 
    Bisky 
    Large Child 
    Mindll
    Bluehh 
    SkyKingTv 
    井擎 井 
    Lorrain 
    Kiessi 
    Lotus 
    IRuby 
    Yoren Aijin 
    Yohann Rbx 
    Samuel Camas 
    MineZefy 
    Peter La ardilla 
    Butnuster445 
    Noah 
    Gyro 
    Doom
    tyzoh
    francerobin6983
    Draco509
    Oranran
    rekindL
    Akimo
    Psychokiller

Other Credits :
    CalebBritannia - Programmer 
    KitanicDemon - Builder
    GeorgeTsakiridis - Programmer
    Localization 1.7.10:
    Abelatox - Spanish 
    Ezequiel - Polish 
    Moore5859 (阿烩丶) - Simplified Chinese 
    Itz Nuk - Brazilian Portuguese 
    Ytekk - French
    tMakotoi - Russian
    Localization 1.14.4:
    BooTrinD - French
    Abelatox - Spanish

'''

[[dependencies.mineminenomi]]
    modId="forge"
    mandatory=true
    versionRange="[28.2.17,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mineminenomi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
